version: 1.0.{build}
branches:
  only:
    - master

image: Visual Studio 2015

environment:
  matrix:
    - platform: win32
      ARCH: win32-msvc9
      configuration: Release
      MSVCVERSION: v90
      MSVCYEAR: "vs2008"
      MSVCABR: "9"
      VC_VER: 9.0
      PYTHONPATH: c:\Python27\
      PY_VER: 27
      BOOST_CFG: >-
          using python : 2.7 : c:/python27/python.exe : c:/python27/include : c:/python27/libs ;
    - platform: x64
      ARCH: x64-msvc9
      configuration: Release
      MSVCVERSION: v90
      MSVCYEAR: "vs2008"
      MSVCABR: "9"
      VC_VER: 9.0
      PYTHONPATH: c:\Python27-x64\
      PY_VER: 27
      BOOST_CFG: >-
          using python : 2.7 : c:/python27-x64/python.exe : c:/python27-x64/include : c:/python27-x64/libs ;

    - platform: win32
      ARCH: win32-msvc14
      configuration: Release
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python36\
      PY_VER: 36
      BOOST_CFG: >-
          using python : 3.6 : c:/python36/python.exe : c:/python36/include : c:/python36/libs ;
    - platform: x64
      ARCH: x64-msvc14
      configuration: Release
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python36-x64\
      PY_VER: 36
      BOOST_CFG: >-
          using python : 3.6 : c:/python36-x64/python.exe : c:/python36-x64/include : c:/python36-x64/libs ;

    - platform: win32
      ARCH: win32-msvc14
      configuration: Release
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python37-x64\
      PY_VER: 37
      BOOST_CFG: >-
          using python : 3.7 : c:/python37/python.exe : c:/python37/include : c:/python37/libs ;
    - platform: x64
      ARCH: x64-msvc14
      configuration: Release
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python37-x64\
      PY_VER: 37
      BOOST_CFG: >-
          using python : 3.7 : c:/python37-x64/python.exe : c:/python37-x64/include : c:/python37-x64/libs ;

init:
  # go to hell Xamarin (see http://help.appveyor.com/discussions/problems/4569)
  - del "C:\Program Files (x86)\MSBuild\4.0\Microsoft.Common.Targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  #RDP from start
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Boost
  - cmd: cd "C:\projects\"
  - appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.zip
  - cmd: 7z -y x boost_1_70_0.zip -oC:\projects\
  #VS2008 patch
  - cmd: cd "C:\projects\"
  - cmd: appveyor DownloadFile https://github.com/menpo/condaci/raw/master/vs2008_patch.zip
  - cmd: 7z -y x vs2008_patch.zip -oC:\projects\vs2008_patch\
  - cmd: if %ARCH%==x64-msvc9 call C:\projects\vs2008_patch\setup_x64.bat
  - cmd: if %ARCH%==x32-msvc9 call C:\projects\vs2008_patch\setup_x86.bat
  - cmd: if %ARCH%==x64-msvc9 copy "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"
  # adding a boost-config.jam file
  - cmd: echo %BOOST_CFG% >> %HOMEDRIVE%%HOMEPATH%\user-config.jam
  - cmd: type %HOMEDRIVE%%HOMEPATH%\user-config.jam
  
install:
  # Setting Visual Compiler
  - cmd: if %ARCH%==win32-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc9 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==x64-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat"
  - cmd: if %ARCH%==win32-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==x64-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: echo "Platform='%Platform%'"
  - cmd: set PYTHONPATH=%PYTHONPATH%
  # building bootstrap
  - cmd: cd C:/projects/boost_1_70_0
  - cmd: C:/projects/boost_1_70_0/bootstrap.bat
  
clone_folder: C:\projects\boost-ci

build:
  parallel: true
  verbosity: minimal
  
build_script:
  # static libraries
  - cmd: cd C:/projects/boost_1_70_0
  - cmd: if %ARCH%==win32-msvc9 b2 -j4 --with-python variant=release toolset=msvc-9.0 address-model=32 threading=multi link=static runtime-link=static install
  - cmd: if %ARCH%==x64-msvc9 b2 -j4 --with-python variant=release toolset=msvc-9.0 address-model=64 threading=multi link=static runtime-link=static install
  - cmd: if %ARCH%==win32-msvc14 b2 -j4 --with-python variant=release toolset=msvc-14.0 address-model=32 threading=multi link=static runtime-link=static install
  - cmd: if %ARCH%==x64-msvc14 b2 -j4 --with-python variant=release toolset=msvc-14.0 address-model=64 threading=multi link=static runtime-link=static install
  # shared libraries
  - cmd: if %ARCH%==win32-msvc9 b2 -j4 --with-python variant=release toolset=msvc-9.0 address-model=32 threading=multi link=shared runtime-link=shared install
  - cmd: if %ARCH%==x64-msvc9 b2 -j4 --with-python variant=release toolset=msvc-9.0 address-model=64 threading=multi link=shared runtime-link=shared install
  - cmd: if %ARCH%==win32-msvc14 b2 -j4 --with-python variant=release toolset=msvc-14.0 address-model=32 threading=multi link=shared runtime-link=shared install
  - cmd: if %ARCH%==x64-msvc14 b2 -j4 --with-python variant=release toolset=msvc-14.0 address-model=64 threading=multi link=shared runtime-link=shared install


after_build:
  - cmd: cd C:/boost
  - cmd: dir
  - 7z a boost-1.70.0_%ARCH%_%PY_VER%.zip C:/boost
  - move boost-1.70.0_%ARCH%_%PY_VER%.zip c:/projects/boost-ci/


on_finish:
  #RDP for finish
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: ./*.zip
