version: 1.0.{build}
branches:
  only:
    - master

image: Visual Studio 2015

environment:
  matrix:
    - platform: x64
      ARCH: x64-msvc9
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 9 2008 Win64"
      MSVCVERSION: v90
      MSVCYEAR: "vs2008"
      MSVCABR: "9"
      VC_VER: 9.0
      PYTHONPATH: c:\Python27-x64\
      PYTHONPATHOMNI: "/cygdrive/c/Python27-x64/python"
      PY_VER: 27
      BOOST_ROOT: C:/local/boost_1_64_0
      BOOST_LIBS: C:/local/boost_1_64_0/lib64-msvc-9.0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
      BOOST_CFG: >-
          using python : 2.7 : c:/python27-x64/python.exe : c:/python27-x64/include : c:/python27-x64/libs ;
    - platform: win32
      ARCH: win32-msvc10
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 10 2010"
      MSVCVERSION: v100
      MSVCYEAR: "vs2010"
      MSVCABR: "10"
      VC_VER: 10.0
      PYTHONPATH: c:\Python34\
      PYTHONPATHOMNI: "/cygdrive/c/Python34/python"
      PY_VER: 34
      BOOST_ROOT: C:/local/boost_1_64_0
      BOOST_LIBS: C:/local/boost_1_64_0/lib32-msvc-10.0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files (x86)\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
      BOOST_CFG: >-
          using python : 3.4 : c:/python34/python.exe : c:/python34/include : c:/python34/libs ;
    - platform: win32
      ARCH: win32-msvc9
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 9 2008"
      MSVCVERSION: v90
      MSVCYEAR: "vs2008"
      MSVCABR: "9"
      VC_VER: 9.0
      PYTHONPATH: c:\Python27\
      PYTHONPATHOMNI: "/cygdrive/c/Python27/python"
      PY_VER: 27
      BOOST_ROOT: C:/local/boost_1_64_0
      BOOST_LIBS: C:/local/boost_1_64_0/lib32-msvc-9.0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files (x86)\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
      BOOST_CFG: >-
          using python : 2.7 : c:/python27/python.exe : c:/python27/include : c:/python27/libs ;
    - platform: x64
      ARCH: x64-msvc10
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 10 2010 Win64"
      MSVCVERSION: v100
      MSVCYEAR: "vs2010"
      MSVCABR: "10"
      VC_VER: 10.0
      PYTHONPATH: c:\Python34-x64\
      PYTHONPATHOMNI: "/cygdrive/c/Python34-x64/python"
      PY_VER: 34
      BOOST_ROOT: C:/local/boost_1_64_0
      BOOST_LIBS: C:/local/boost_1_64_0/lib64-msvc-10.0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
      BOOST_CFG: >-
          using python : 3.4 : c:/python34-x64/python.exe : c:/python34-x64/include : c:/python34-x64/libs ;
    - platform: x64
      ARCH: x64-msvc12
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      MSVCVERSION: v120
      MSVCYEAR: "vs2013"
      MSVCABR: "13"
      VC_VER: 13.0
      PYTHONPATH: c:\Python34-x64\
      PYTHONPATHOMNI: "/cygdrive/c/Python34-x64/python"
      PY_VER: 34
      BOOST_ROOT: C:/local/boost_1_64_0
      BOOST_LIBS: C:/local/boost_1_64_0/lib64-msvc-12.0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
      BOOST_CFG: >-
          using python : 3.4 : c:/python34-x64/python.exe : c:/python34-x64/include : c:/python34-x64/libs ;
    - platform: x64
      ARCH: x64-msvc14
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python35-x64\
      PYTHONPATHOMNI: "/cygdrive/c/Python35-x64/python"
      PY_VER: 35
      BOOST_ROOT: C:/local/boost_1_64_0
      BOOST_LIBS: C:/local/boost_1_64_0/lib64-msvc-14.0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1    
      BOOST_CFG: >-
          using python : 3.5 : c:/python35-x64/python.exe : c:/python35-x64/include : c:/python35-x64/libs ;
    - platform: x64
      ARCH: x64-msvc14
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python36-x64\
      PYTHONPATHOMNI: "/cygdrive/c/Python36-x64/python"
      PY_VER: 36
      BOOST_ROOT: C:/local/boost_1_64_0
      BOOST_LIBS: C:/local/boost_1_64_0/lib64-msvc-14.0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1    
      BOOST_CFG: >-
          using python : 3.6 : c:/python36-x64/python.exe : c:/python36-x64/include : c:/python36-x64/libs ;
init:
  # go to hell Xamarin (see http://help.appveyor.com/discussions/problems/4569)
  - del "C:\Program Files (x86)\MSBuild\4.0\Microsoft.Common.Targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  #RDP from start
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Boost
  - cmd: cd "C:\projects\"
  - cmd: md boost_build
  - cmd: cd "C:\projects\"
  - appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.zip
  - cmd: 7z -y x boost_1_64_0.zip -oC:\projects\boost_build\
  #Pthread-Win32
  - cmd: cd "C:\projects\"
  - cmd: md pthreads-win32
  - cmd: cd "C:\projects\"
  - appveyor DownloadFile "http://www.mirrorservice.org/sites/sources.redhat.com/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip"
  - cmd: 7z -y x pthreads-w32-2-9-1-release.zip -oC:\projects\pthreads-win32\
  #VS2008 patch
  - cmd: cd "C:\projects\"
  - cmd: appveyor DownloadFile https://github.com/menpo/condaci/raw/master/vs2008_patch.zip
  - cmd: 7z -y x vs2008_patch.zip -oC:\projects\vs2008_patch\
  - cmd: if %ARCH%==x64-msvc9 call C:\projects\vs2008_patch\setup_x64.bat
  - cmd: if %ARCH%==x32-msvc9 call C:\projects\vs2008_patch\setup_x86.bat
  - cmd: if %ARCH%==x64-msvc9 copy "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"
  # adding a boost-config.jam file
  - cmd: echo %BOOST_CFG% >> %HOMEDRIVE%%HOMEPATH%\user-config.jam
  - cmd: type %HOMEDRIVE%%HOMEPATH%\user-config.jam
  - cmd: cd "C:\projects\boost-ci"
  
install:
  # Setting Visual Compiler
  - cmd: cd "C:\projects\"
  - cmd: if %ARCH%==win32-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc9 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==x64-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat"
  - cmd: if %ARCH%==win32-msvc10 call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc10 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==x64-msvc10 call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 
  - cmd: if %ARCH%==x64-msvc12 call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cmd: if %ARCH%==x64-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: echo "Generator='%CMAKE_GENERATOR%'"
  - cmd: echo "Platform='%Platform%'"
  - cmd: set PYTHONPATH=%PYTHONPATH%
  # building bootstrap
  - cmd: cd C:/projects/boost_build/boost_1_64_0
  - cmd: C:/projects/boost_build/boost_1_64_0/bootstrap.bat
  
clone_folder: C:\projects\boost-ci

build:
  parallel: true
  verbosity: minimal
  
build_script:
  - cmd: cd C:/projects/boost_build/boost_1_64_0
  - cmd: if %ARCH%==win32-msvc9 b2 toolset=msvc-9.0 address-model=32 install link=static runtime-link=static,shared
  - cmd: if %ARCH%==x64-msvc9 b2 toolset=msvc-9.0 address-model=64 install link=static runtime-link=static,shared
  - cmd: if %ARCH%==win32-msvc10 b2 toolset=msvc-10.0 address-model=32 install link=static runtime-link=static,shared
  - cmd: if %ARCH%==x64-msvc10 b2 toolset=msvc-10.0 address-model=64 install link=static runtime-link=static,shared
  - cmd: if %ARCH%==x64-msvc12 b2 toolset=msvc-12.0 address-model=64 install link=static runtime-link=static,shared
  - cmd: if %ARCH%==x64-msvc14 b2 toolset=msvc-14.0 address-model=64 install link=static runtime-link=static,shared



after_build:
  - cmd: cd C:/boost
  - cmd: dir
  - 7z a boost-1.64_%ARCH%_%PY_VER%.zip C:/boost
  - move boost-1.64_%ARCH%_%PY_VER%.zip c:/projects/boost-ci/


on_finish:
  #RDP for finish
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: ./*.zip
